services:
  frp-server:
    build: .
    container_name: "frp-server"
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "9296-9299:9296-9299"
      - "9296-9299:9296-9299/udp"
        # - "9299:9299"
        # - "9297:9297"
    volumes:
      - ./frps.ini:/frp/frps.ini
    environment:
      - ARGS=frps
