version: "3"

services:
  zerotier-moon:
    build: .
    container_name: "zerotier-moon"
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "9993:9993"
    volumes:
      - ./config:/var/lib/zerotier-one
    entrypoint:
      - /startup.sh
      - "-4"
      - "114.214.170.191"
